# Generated by Django 6.0.1 on 2026-01-19 09:33

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompanyProfile', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='job_model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jobtitle', models.CharField(max_length=250)),
                ('vocancyCode', models.CharField(blank=True, max_length=50)),
                ('vocancynum', models.IntegerField(default=0)),
                ('job_location_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], default='onsite')),
                ('category', models.CharField(choices=[('Information Technology', 'It'), ('HR', 'Hr'), ('Design', 'Design')], default='Design')),
                ('job_address', models.CharField(blank=True, max_length=250)),
                ('createat', models.DateField(auto_now=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('job_descibstion', ckeditor.fields.RichTextField(default='')),
                ('job_summery', ckeditor.fields.RichTextField(default='')),
                ('submision_guide', ckeditor.fields.RichTextField(default='')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyProfile.company_db_model')),
            ],
        ),
        migrations.CreateModel(
            name='job_application_model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apply_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_link', models.CharField(blank=True, max_length=250, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicantuser', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapp', to='jobs.job_model')),
            ],
            options={
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
