# Generated by Django 6.0.1 on 2026-04-01 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_model',
            name='category',
            field=models.CharField(choices=[('Information Technology', 'It'), ('HR', 'Hr'), ('Design', 'Design')], default='Design'),
        ),
        migrations.AlterField(
            model_name='job_model',
            name='job_location_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], default='onsite'),
        ),
        migrations.CreateModel(
            name='saved_job_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedjob', to='jobs.job_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saveduser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job', 'user')},
            },
        ),
    ]
