# Generated by Django 6.0.1 on 2026-04-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_model_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_model',
            name='category',
            field=models.CharField(choices=[('Information Technology', 'It'), ('HR', 'Hr'), ('Design', 'Design')], default='Design'),
        ),
        migrations.AlterField(
            model_name='job_model',
            name='job_location_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], default='onsite'),
        ),
    ]
