# Generated by Django 6.0.1 on 2026-04-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_application_model_cover_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_application_model',
            name='apply_date',
        ),
        migrations.AlterField(
            model_name='job_model',
            name='category',
            field=models.CharField(choices=[('Information Technology', 'It'), ('HR', 'Hr'), ('Design', 'Design')], default='Design'),
        ),
        migrations.AlterField(
            model_name='job_model',
            name='job_location_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], default='onsite'),
        ),
    ]
