# Generated by Django 6.0.1 on 2026-01-19 09:23

import CompanyProfile.models
import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_db_model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=250)),
                ('company_name_abravetion', models.CharField(blank=True, max_length=250)),
                ('company_summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('Company_logo', models.ImageField(blank=True, upload_to=CompanyProfile.models.Company_logo_path)),
                ('Company_cover_Photo', models.ImageField(blank=True, upload_to=CompanyProfile.models.Company_cover_path)),
                ('activity_status', models.BooleanField(default=True)),
                ('WEBSITE', models.CharField(blank=True)),
                ('Location', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
