# Generated by Django 6.0.1 on 2026-01-19 09:23

import ControlUser.models
import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(blank=True, max_length=20)),
                ('skill_disc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skillforuser', to='ControlUser.skill')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_title', models.CharField(blank=True, max_length=250)),
                ('job_industry', models.CharField(blank=True, max_length=250, null=True)),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=50)),
                ('nationality', models.CharField(default='afghan', max_length=50)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=ControlUser.models.user_image_path)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to=ControlUser.models.user_cover_path)),
                ('resume_pdf', models.FileField(blank=True, null=True, upload_to=ControlUser.models.user_pdf_path)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('create_At', models.DateField(default=django.utils.timezone.now)),
                ('Skill', models.ManyToManyField(related_name='usersskilssuniqe', through='ControlUser.UserSkill', to='ControlUser.skill')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userskills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill')},
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('project_link', models.CharField(blank=True, max_length=250, null=True)),
                ('related_industry', models.CharField(blank=True, max_length=50, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project_name', 'related_industry')},
            },
        ),
        migrations.CreateModel(
            name='UserExp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('exp_desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'title', 'company_name', 'location')},
            },
        ),
        migrations.CreateModel(
            name='UserEdu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('SchoolName', models.CharField(max_length=50)),
                ('degreelevel', models.CharField(blank=True, max_length=50, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('school_desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eduuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'SchoolName', 'degreelevel')},
            },
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('certificate_name', models.CharField(max_length=50)),
                ('certificate_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('certificate_link', models.CharField(blank=True, max_length=250, null=True)),
                ('instatution', models.CharField(blank=True, max_length=50, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ceruser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'certificate_name', 'instatution')},
            },
        ),
    ]
