# Generated by Django 6.0.1 on 2026-04-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlUser', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=50),
        ),
    ]
